### ISSUE TITLE
Need Help with rails associations with counting duplicate associations

### ISSUE THREAD

**Issue by EricKwong** [EricKwong/Savage#5]
## CONTEXT

@harimohanraj89 @DrRobotmck @williamfshaw @bigtone1284

##### WHAT USER STORY YOU ARE WORKING ON:

A user should have many monsters encounters where monsters encounters of the same type are possible.

##### WHAT YOU ARE TRYING TO DO:

I am trying to set up associates for players and monsters where the same monster object can be associated with the player more then once. 

##### DETAILED DESCRIPTION OF THE BUG/ERROR:

I'm not sure how to approach.

## WHAT I'VE TRIED

I've tried setting up a through join table with a counter but doesn't seem to be working.

## QUESTION

May I get some assistance on this?

:heart:
A meticulous and troubled student

**Comment by bigtone1284** [comment]
So, You want a table that tracks the unique encounters between people and monsters, AND encounters are unique based on like the time they happened at.  

To abstract it a little bit, you have two database entities that are related through individual instances to which they are linked.  

That relationship sounds a lot like the relationship between Patients, Doctors AND their appointments.  Patients can have many doctors and vice versa, BUT appointments are multiple instances where patients and doctors are linked.  

I bring up the example of patients and doctors and it's similarity to your situation because in the Active Record docs, this is example is used to demonstrate a relationship known as has many through.

http://guides.rubyonrails.org/association_basics.html#the-has-many-through-association

Give it a read.

**Comment by bigtone1284** [comment]
So rather than keep a counter of encounters on your table, I would just use the database to track each encounter that occurs in your monster-people universe.  Then, I would right the necessary class and instance methods needed  in order to get (for example) the most frequent encounters or a sorted list of all  one persons encounters.

**Comment by bigtone1284** [comment]
To be candid, I would implement the exact has many through relationship in the docs but using the entities in your universe and then write methods to filter, order, sort, find, etc.

**Comment by bigtone1284** [comment]
taken
